# Set the default log level to TRACE to see everything
org.slf4j.simpleLogger.defaultLogLevel=debug
# Optional: Show more details in the log output
org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss
org.slf4j.simpleLogger.showThreadName=true
org.slf4j.simpleLogger.showLogName=true

org.slf4j.simpleLogger.logFile=logs/modforge.log