package com.nukuhack.modforge.backend.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum BuffParamMap {
	// Stats
	STRENGTH("strength", "Stat Strength", "Affects the character's physical power, influencing melee damage and the ability to carry heavy equipment."),
	AGILITY("agility", "Stat Agility", "Determines the character's speed, reflexes, and effectiveness with ranged weapons or dodging."),
	VITALITY("vitality", "Stat Vitality", "Represents physical resilience, influencing health regeneration and endurance."),
	SPEECH("speech", "Stat Speech", "Affects persuasion in dialogues, trading outcomes, and social interactions."),
	VISION("vision", "Stat Vision", "Modifies how well the character can see, especially in darkness or at distance."),
	HEARING("hearing", "Stat Hearing", "Determines how well the character can detect sounds, such as approaching enemies or environmental cues."),
	BARTER("barter", "Stat Barter", "Influences the effectiveness of trading, affecting prices when buying or selling goods."),
	COURAGE("courage", "Stat Courage", "Reflects the character's bravery, possibly affecting resistance to fear or fleeing behavior."),
	STORY_PROGRESS("storyProgress", "Stat Story Progress", "Tracks the advancement through the main storyline and major quest milestones."),
	PRESTIGE("prestige", "Stat Prestige", "Represents the character's reputation and standing within the world, possibly influencing NPC reactions."),
	
	// Skills
	STEALTH("stealth", "Skill Stealth", "Determines how effectively the player can move undetected, sneak past enemies, and perform stealth actions."),
	HORSE_RIDING("horse_riding", "Skill Horse Riding", "Improves control and performance while riding a horse, affecting speed, maneuverability, and mounted combat."),
	FENCING("fencing", "Skill Fencing", "Measures skill with one-handed bladed weapons, such as sabres or rapiers."),
	BARD("bard", "Skill Bard", "Enhances social and entertainment abilities, possibly affecting speech, persuasion, and interactions in taverns or court."),
	THIEVERY("thievery", "Skill Thievery", "Affects the ability to steal, pick locks, and avoid detection while committing crimes."),
	PICKPOCKETING_OBSOLETE("pickpocketing_obsolete", "Skill Pickpocketing Obsolete", "An outdated or deprecated value once related to stealing items directly from NPCs."),
	ALCHEMY("alchemy", "Skill Alchemy", "Improves potion brewing and the identification of alchemical ingredients and effects."),
	COOKING("cooking", "Skill Cooking", "Determines the player's ability to prepare meals that restore health or provide temporary buffs."),
	CRAFTSMANSHIP("craftsmanship", "Skill Craftsmanship", "General skill for crafting various items, potentially covering tailoring, leatherwork, or construction."),
	SMITHING_OBSOLETE("smithing_obsolete", "Skill Smithing Obsolete", "A deprecated skill related to forging or repairing weapons and armor."),
	FISHING("fishing", "Skill Fishing", "Improves success at catching fish, possibly affecting yield and quality."),
	MINING("mining", "Skill Mining", "Determines how efficiently the player can extract ores or materials from mines."),
	FIRST_AID("first_aid", "Skill First Aid", "Affects the ability to treat injuries, heal wounds, or stabilize characters in critical condition."),
	DRINKING("drinking", "Skill Drinking", "Represents alcohol tolerance and related perks, possibly reducing negative effects of intoxication."),
	SURVIVAL("survival", "Skill Survival", "General wilderness knowledge, such as tracking, gathering herbs, or navigating terrain."),
	DEFENSE("defense", "Skill Defense", "Influences blocking, parrying, and overall resistance during combat."),
	WEAPON_SWORD("weapon_sword", "Skill Weapon Sword", "Determines effectiveness when using swords in combat, including damage and combos."),
	HEAVY_WEAPONS("heavy_weapons", "Skill Heavy Weapons", "Represents proficiency with large, heavy weapons such as axes or maces."),
	WEAPON_BOW_OBSOLETE("weapon_bow_obsolete", "Skill Weapon Bow Obsolete", "A deprecated skill value once associated with archery."),
	MARKSMANSHIP("marksmanship", "Skill Marksmanship", "Measures precision and effectiveness with ranged weapons, especially bows and crossbows."),
	WEAPON_SHIELD("weapon_shield", "Skill Weapon Shield", "Determines proficiency with shields, affecting blocking efficiency and stamina use in defense."),
	WEAPON_MACE_OBSOLETE("weapon_mace_obsolete", "Skill Weapon Mace Obsolete", "A deprecated value once used to represent skill with blunt weapons such as maces."),
	WEAPON_DAGGER("weapon_dagger", "Skill Weapon Dagger", "Measures effectiveness in combat using daggers, including quick attacks and stealth kills."),
	WEAPON_LARGE("weapon_large", "Skill Weapon Large", "Represents the player's skill with two-handed or oversized weapons like greatswords or polearms."),
	WEAPON_UNARMED("weapon_unarmed", "Skill Weapon Unarmed", "Affects damage and effectiveness in hand-to-hand combat without weapons."),
	HERBALISM_OBSOLETE("herbalism_obsolete", "Skill Herbalism Obsolete", "An outdated skill once related to harvesting herbs and preparing natural remedies."),
	SCHOLARSHIP("scholarship", "Skill Scholarship", "Reflects knowledge of reading, writing, and scholarly pursuits such as history or theology."),
	TAILORING("tailoring", "Skill Tailoring", "Enables crafting and repairing of clothing and light armor."),
	ARMOURER("armourer", "Skill Armourer", "Affects the ability to craft, maintain, or enhance armor pieces."),
	WEAPONSMITHING("weaponsmithing", "Skill Weaponsmithing", "Determines proficiency in forging and improving weapons."),
	SHOEMAKING("shoemaking", "Skill Shoemaking", "Covers crafting and repairing footwear, possibly affecting movement and stealth bonuses."),
	GUNSMITHING("gunsmithing", "Skill Gunsmithing", "Relates to maintenance and crafting of firearms, if present in the game."),
	BOWYERY("bowyery", "Skill Bowyery", "Involves the crafting and tuning of bows for better performance in ranged combat."),
	GAMBLING("gambling", "Skill Gambling", "Affects outcomes in games of chance, including dice or betting interactions."),
	HOUNDMASTER("houndmaster", "Skill Houndmaster", "Reflects ability to command, train, and use dogs in hunting or combat situations."),
	
	// S States
	HEALTH("health", "S State Health", "Represents the character's overall vitality; when it reaches zero, the player dies."),
	STAMINA("stamina", "S State Stamina", "Determines how long the player can perform physical actions like running, fighting, or blocking before becoming fatigued."),
	EXHAUST("exhaust", "S State Exhaust", "Indicates how tired the character is, possibly affecting movement, perception, or combat performance."),
	HUNGER("hunger", "S State Hunger", "Tracks the need for food; high hunger levels reduce performance or lead to penalties."),
	KARMA("karma", "S State Karma", "Reflects the moral alignment of the character's actions, potentially influencing how NPCs react or whether certain options are available."),
	ALCOHOLISM_STATE("alcoholism", "S State Alcoholism", "Represents the player's dependence on alcohol; may cause withdrawal effects or penalties when sober."),
	
	// Inter
	ADE("ade", "Inter Armor Defense", "Affects the defensive value provided by armor, reducing incoming physical damage."),
	UAT("uat", "Inter Unarmed Attack", "Determines the strength or effectiveness of unarmed strikes in combat."),
	WAT("wat", "Inter Weapon Attack", "Influences the damage output of weapon-based attacks."),
	WAC("wac", "Inter Weapon Attack Cost", "Represents how much stamina is consumed when performing a weapon attack."),
	AHM("ahm", "Inter Attack From Horse Mod", "Modifies effectiveness or damage of attacks performed while mounted on horseback."),
	RTM("rtm", "Inter Rider Threats To Horse Morale", "Affects how enemy presence or actions impact the morale or behavior of the player's horse."),
	ACT("act", "Inter Movement Proficiency", "Indicates how efficiently the character moves, potentially reducing stamina cost or increasing speed."),
	ASP("asp", "Inter Attack Speed 01", "Determines how quickly the player can perform attacks in combat."),
	PBS("pbs", "Inter Perfect Block Slot 01", "Increases the window of opportunity for executing a perfect block."),
	CLI("cli", "Inter Clinch Advantage", "Affects success in clinch situations, determining dominance during close combat grapples."),
	HLH("hlh", "Inter Health Loss Hit", "Modifies the amount of health lost when taking a hit."),
	SLH("slh", "Inter Stamina Loss Hit", "Determines how much stamina is lost when receiving an enemy attack."),
	SLS("sls", "Inter Stamina Loss Blocking Shield", "Represents the stamina cost of blocking attacks with a shield."),
	DIG("dig", "Inter Digestion Speed", "Affects how quickly consumed food is digested, impacting hunger and stamina over time."),
	EXH("exh", "Inter Exhaustion Speed", "Determines how rapidly exhaustion accumulates during physical activities."),
	HOD("hod", "Inter Hangover Duration", "Modifies how long negative effects from alcohol last after sobering up."),
	PSP("psp", "Inter Potion Heal Speed", "Affects the speed at which health potions take effect."),
	LCS("lcs", "Inter Lock Cursor Shake", "Controls how much the cursor shakes while lock picking, impacting difficulty."),
	SRG("srg", "Inter Stamina Regen", "Determines how quickly stamina regenerates over time."),
	SCO("sco", "Inter Stamina Consumption", "Represents the general stamina cost of actions like attacking or running."),
	SRB("srb", "Inter Stamina Regen Block", "Modifies stamina regeneration while blocking attacks."),
	SRA("sra", "Inter Stamina Regen Attack", "Affects how quickly stamina regenerates after executing an attack."),
	ARD("ard", "Inter Archery Stamina Drain", "Modifies how much stamina is drained while aiming or drawing a bow."),
	SKP("skp", "Inter Stealth Kill Probability", "Determines the likelihood of successfully performing a stealth kill without being detected."),
	RST("rst", "Inter Relative Stamina Max", "Modifies the character's maximum stamina relative to their base value."),
	PDP("pdp", "Inter Pull Down Probability", "Represents the chance of successfully pulling an enemy to the ground during a grappling move."),
	EEP("eep", "Inter Random Event Escape Probability", "Influences the likelihood of escaping from hostile encounters or random world events."),
	LPD("lpd", "Inter Lock picking Difficulty", "Adjusts the complexity of lock picking interactions, making them easier or harder."),
	LPN("lpn", "Inter Lock picking Noise Multiplier", "Modifies the amount of noise generated while lock picking, affecting the chance of being heard."),
	AIN("ain", "Inter Attack Injury", "Determines the chance or severity of injuries caused to opponents during attacks."),
	HIN("hin", "Inter Hit Injury", "Represents how likely the player is to suffer injuries when hit."),
	FAE("fae", "Inter First Aid Efficiency", "Affects how effectively first aid heals or stabilizes the player."),
	DEE("dee", "Inter Damage To Enemy Armor", "Modifies the amount of damage dealt to an opponent's armor."),
	DEW("dew", "Inter Damage To Enemy Weapon", "Affects the durability loss of an enemy's weapon when struck or parried."),
	OSB("osb", "Inter Opponent Stamina Loss Blocking", "Represents the stamina loss incurred by enemies when their attacks are blocked."),
	DSL("dsl", "Inter Dodge Slot", "Increases the window or effectiveness of performing a dodge maneuver."),
	COS("cos", "Inter Combo Slot 01", "Expands the number or timing of available combo attacks."),
	PAC("pac", "Inter Weapon Poison Apply Chance", "Determines how likely poison is to be applied to a weapon strike."),
	LPB("lpb", "Inter Lock picking Lock-pick Break Chance", "Modifies the chance that a lock-pick will break during lock picking."),
	RES("res", "Inter Recognition Speed", "Affects how quickly NPCs recognize or identify the player."),
	ORS("ors", "Inter Observer Recognition Speed", "Modifies how fast other characters (observers) notice the player's actions or presence."),
	PTP("ptp", "Inter Pickpocketing Time Penalty", "Adds or reduces penalty time when pickpocketing, impacting success chance."),
	SHR("shr", "Inter Sleep Health Regen Modifier", "Changes how much health is restored during sleep."),
	SER("ser", "Inter Sleep Exhaust Regen Modifier", "Determines how much exhaustion is recovered while sleeping."),
	PIM("pim", "Inter Poison Immunity", "Indicates resistance or immunity to poison effects."),
	ALD("ald", "Inter Alcoholism Debuff Modifier", "Adjusts the severity of penalties from alcoholism, such as reduced stats or blurred vision."),
	AAM("aam", "Inter Alcohol Absorption", "Determines how quickly alcohol is absorbed, affecting how fast intoxication sets in."),
	UAB("uab", "Inter Unaware Victim Attack Bonus Mod", "Provides a damage or success bonus when attacking unaware or unsuspecting enemies."),
	FHM("fhm", "Inter Food Health Modifier", "Influences how food affects health, potentially boosting or reducing its healing effect."),
	FNE("fne", "Inter Fine", "Represents monetary penalties applied to the player for crimes or violations."),
	DTH("dth", "Inter Damage To Heart", "Indicates damage dealt to the heart, which may cause severe health loss or fatal conditions."),
	DTD("dtd", "Inter Damage To Head", "Affects how much damage is delivered to the head area during combat."),
	TDH("tdh", "Inter Taken Damage To Head", "Modifies the damage the player receives when struck on the head."),
	ADC("adc", "Inter Additional Dog Clinch Mod", "Provides a modifier to dog-assisted clinch actions, improving their effectiveness."),
	SLA("sla", "Inter Slash Attack", "Modifies damage or effectiveness of slashing attacks with edged weapons."),
	STA("sta", "Inter Stab Attack", "Modifies damage or effectiveness of stabbing attacks with pointed weapons."),
	SSA("ssa", "Inter Smash Attack", "Affects the power or impact of blunt or smashing attacks."),
	WSR("wsr", "Inter Weapon Strength Requirement", "Sets the strength required to effectively wield a weapon."),
	WAR("war", "Inter Weapon Agility Requirement", "Sets the agility required to effectively wield a weapon."),
	WRS("wrs", "Inter Weapon Requirement Strength Stat", "Links weapon usability to the player's strength attribute."),
	WRA("wra", "Inter Weapon Requirement Agility Stat", "Links weapon usability to the player's agility attribute."),
	EFC("efc", "Inter Event Flee Chance", "Determines the likelihood of successfully fleeing from scripted or random events."),
	DSC("dsc", "Inter Dodge Stamina Cost", "Modifies how much stamina is consumed when performing a dodge."),
	WDE("wde", "Inter Weapon Defense", "Represents the weapon's defensive capability when used to block or parry."),
	EWD("ewd", "Inter Enemy Weapon Defense", "Indicates how well enemy weapons perform in defense, impacting parry and block success."),
	SCV("scv", "Inter Skill Check Skill Value", "Determines the skill value used when performing a skill check."),
	SCX("scx", "Inter Skill Check Skill XP", "Modifies how much experience is gained from successful skill checks."),
	CAT("cat", "Inter Clinch Attack", "Affects effectiveness or damage of attacks initiated from a clinch."),
	ACM("acm", "Inter Attack Charging Mod", "Modifies the effect of charging an attack before release, potentially increasing damage."),
	RAT("rat", "Inter Ranged Weapon Attack", "Determines effectiveness or damage of attacks using ranged weapons like bows or crossbows."),
	RLS("rls", "Inter Reload Speed", "Determines how quickly ranged weapons can be reloaded."),
	PTW("ptw", "Inter Player Time Warp", "Modifies the player's perception of time flow, potentially speeding up or slowing down actions."),
	ALA("ala", "Inter Alchemy Potion Amount", "Affects the quantity of potion produced in alchemy crafting."),
	APQ("apq", "Inter Alchemy Potion Quality", "Determines the quality level of potions created through alchemy, influencing their effectiveness."),
	BID("bid", "Inter Blocking Item Damage", "Modifies damage taken by items used for blocking, affecting their durability loss."),
	FOB("fob", "Inter Feint Opponent Block Probability", "Influences the chance that an opponent will successfully block a feint attack."),
	ODE("ode", "Inter Opponent Armor Defense", "Represents how much damage the opponent's armor can absorb or reduce."),
	DMD("dmd", "Inter Dog Morale Decay By Time", "Controls how quickly a dog's morale decreases over time when inactive or not fed."),
	DMH("dmh", "Inter Dog Morale Decay By Hit", "Determines how much a dog's morale decreases when it is hit or takes damage."),
	DRN("drn", "Inter Dog Return Time", "Specifies the time it takes for a dog to return to the player after being called or released."),
	BQC("bqc", "Inter Bed Quality Clamped", "Represents the effective bed quality, limited to a maximum value for sleep benefits."),
	BQY("bqy", "Inter Bed Quality", "Determines the overall quality of a bed, affecting sleep regeneration and comfort."),
	IFC("ifc", "Inter Item Fade Coefficiency", "Controls how quickly items visually fade or degrade in appearance over time."),
	PWC("pwc", "Inter Poison Weapon Charge Count", "Indicates how many charges of poison can be applied to a weapon before depletion."),
	PAA("paa", "Inter Poison Ammo Apply Count", "Determines how many ammo rounds can be coated with poison before reapplication is needed."),
	ITD("itd", "Inter Item Decay", "Modifies the rate at which items deteriorate or lose durability."),
	RKM("rkm", "Inter Repair Kit Repair Price Modifier", "Adjusts the cost effectiveness of repair kits used on items or equipment."),
	RHM("rhm", "Inter Forced Horse Rear Moral Hit Multiplier", "Modifies the impact of morale damage to horses when they rear or are startled."),
	PHV("phv", "Inter Potion Heal Value", "Determines how much health is restored by consuming potions."),
	BNV("bnv", "Inter Beer Nutrition Value", "Represents the nutritional value provided by consuming beer."),
	PNV("pnv", "Inter Potion Nutrition Value", "Indicates the nutrition gained from consuming potions."),
	FNV("fnv", "Inter Food Nutrition Value", "Represents the nutritional content of food items."),
	APS("aps", "Inter Ammo Projectile Speed", "Determines the flight speed of ammunition projectiles like arrows or bolts."),
	FBM("fbm", "Inter Foot Step In Bushes Multiplier", "Modifies the noise or detection chance when stepping through bushes or foliage."),
	TDM("tdm", "Inter Timed Delta Multiplier", "Affects time-based multipliers for buffs or debuffs, adjusting their duration or strength over time."),
	CPS("cps", "Inter Inventory Capacity Per Strength", "Increases inventory carrying capacity based on the player's strength stat."),
	SPV("spv", "Inter Stamina Per Vitality", "Modifies stamina regeneration or maximum stamina based on vitality attribute."),
	PCT("pct", "Inter Pickpocketing Charge Time Ratio", "Alters the time required to prepare or charge a pickpocket attempt."),
	NHP("nhp", "Inter Non Healing Potion Digestion Speed", "Determines how quickly non-healing potions are metabolized and leave the system."),
	NRB("nrb", "Inter Nervousness For Recognition Border", "Represents the nervousness threshold affecting NPC recognition or suspicion of the player."),
	BTD("btd", "Inter Blood Transfer From Damage", "Indicates how much blood is lost or transferred due to damage taken."),
	
	// Deriv
	CHARISMA("charisma", "Deriv Stat Charisma", "Represents the character's charm and social influence in interactions."),
	RCH("rch", "Deriv Stat Relative Charisma", "Measures charisma relative to other characters, influencing social dynamics."),
	CSE("cse", "Deriv Stat Charisma Strength Effect", "Modifies the effect of charisma based on character's physical strength."),
	VIB("vib", "Deriv Stat Visibility", "Determines how visible the character is to NPCs or enemies."),
	EVI("evi", "Deriv Stat Equip Visibility", "Measures the visibility impact of equipped items on the character."),
	CON("con", "Deriv Stat Conspicuousness", "Indicates how conspicuous or noticeable the character is in their environment."),
	MST("mst", "Deriv Stat Max Stamina", "The maximum stamina pool the character can have."),
	MHS("mhs", "Deriv Stat Max Healthy Stamina", "Maximum stamina available when the character is in healthy condition."),
	HLT("hlt", "Deriv Stat Healthiness", "Represents the overall health state of the character."),
	SDT("sdt", "Deriv Stat Stamina Derivation", "Calculation or source determining stamina values."),
	FOV("fov", "Deriv Stat Field Of View", "The angle or range of vision the character can perceive."),
	VIR("vir", "Deriv Stat View Radius", "The radius or distance the character can see or detect objects."),
	TSR("tsr", "Deriv Stat Target Search Radius", "Defines how far the character can search for targets or interactable."),
	DTF("dtf", "Deriv Stat Dice Throw Fixing", "Modifies dice roll results to affect randomness in favor of the player."),
	DBF("dbf", "Deriv Stat Dice Bust Fixing", "Adjusts the chance to avoid a critical failure on dice rolls."),
	PT1("pt1", "Deriv Stat Perfect Throw Multiplier 1", "Multiplier applied for perfect dice throw with one success."),
	PT5("pt5", "Deriv Stat Perfect Throw Multiplier 5", "Multiplier applied for perfect dice throw with five successes."),
	DAI("dai", "Deriv Stat Dice AI Difficulty", "Adjusts AI difficulty related to dice games or chances."),
	BNC("bnc", "Deriv Stat Dice Badge No Consumption Probability", "Probability that dice badges are not consumed after use."),
	HAC("hac", "Deriv Stat Haggle Additional Chances", "Increases additional chances for successful haggling or trading."),
	HDE("hde", "Deriv Stat Haggle Denial", "Reduces chances of haggling failures or denials."),
	LFU("lfu", "Deriv Stat Lock Fail Unlock Probability", "Chance to unlock a lock after a failed attempt."),
	LIO("lio", "Deriv Stat Lock Instant Open Difficulty", "Difficulty of opening a lock instantly without tools."),
	CAP("cap", "Deriv Stat Inventory Capacity", "Maximum carrying capacity of the character's inventory."),
	ALO("alo", "Deriv Stat Armor Load", "Total weight or burden of armor worn by the character."),
	OAD("oad", "Deriv Stat Overall Armor Defense", "Cumulative defensive value provided by all worn armor."),
	OWA("owa", "Deriv Stat Overall Weapon Attack", "Total offensive power from all weapons equipped."),
	WUD("wud", "Deriv Stat Weapon Usage Damage Modifier", "Modifies damage caused by weapon usage over time or wear."),
	LVL("lvl", "Deriv Stat Main Level", "The character's main progression or level value."),
	NOI("noi", "Deriv Stat Noise", "Amount of noise generated by the character, influencing stealth."),
	FSM("fsm", "Deriv Stat Footstep Sound Multiplier", "Multiplier affecting the loudness of footsteps."),
	NRS("nrs", "Deriv Stat Normalized Run Speed", "The character's normalized running speed factoring all modifiers."),
	RSB("rsb", "Deriv Stat Run Speed Base", "The base running speed before any modifiers or effects are applied."),
	NSB("nsb", "Deriv Stat Normalized Run Speed Base", "Normalized base run speed used for calculations to balance speed values."),
	RSA("rsa", "Deriv Stat Relative Movement Speed Addition", "Additional movement speed modifier relative to base speed."),
	BLE("ble", "Deriv Stat Bleeding Total", "Represents the total bleeding damage affecting the character."),
	IBI("ibi", "Deriv Stat Injury Bleeding Interval", "The interval or frequency at which bleeding damage is applied."),
	BOW("bow", "Deriv Stat Body Weight", "The overall weight of the character's body affecting stamina and movement."),
	COW("cow", "Deriv Stat Collision Weight", "Weight used in collision physics impacting knockbacks and pushes."),
	ACO("aco", "Deriv Stat Armor Collision Weight", "Collision weight specifically contributed by worn armor."),
	CAW("caw", "Deriv Stat Carried Weight", "Total weight of all items currently carried by the character."),
	RCW("rcw", "Deriv Stat Relative Carried Weight", "Carried weight relative to the character's carrying capacity."),
	MOR("mor", "Deriv Stat Morale", "Current morale level influencing combat effectiveness and behavior."),
	DEM("dem", "Deriv Stat Default Morale", "Baseline morale value used in the absence of modifiers."),
	MCF("mcf", "Deriv Stat Morale Context Fading Modifier", "Rate at which morale effects fade over time depending on context."),
	OBE("obe", "Deriv Stat Obedience", "Measure of how obedient or compliant the character is to commands or authority."),
	PSR("psr", "Deriv Stat POI Search Radius", "Radius within which the character can detect Points Of Interest."),
	XPM("xpm", "Deriv Stat XP Multiplier", "Multiplier that affects the amount of experience points gained."),
	OSL("osl", "Deriv Stat Oversleepness", "Degree to which the character is oversleeping affecting wakefulness."),
	MOS("mos", "Deriv Stat Max Oversleepness", "Maximum allowable oversleepness before penalties apply."),
	ORE("ore", "Deriv Stat Overreadness", "Level of mental fatigue due to excessive reading or focus."),
	CAF("caf", "Deriv Stat Caffeine", "Amount of caffeine in the character's system affecting alertness."),
	RDQ("rdq", "Deriv Stat Reading Quality", "Quality metric representing effectiveness of reading activities."),
	ERQ("erq", "Deriv Stat Effective Reading Quality", "Actual impact of reading quality after modifiers."),
	SLE("sle", "Deriv Stat Sleeping", "Current sleep state or duration influencing recovery."),
	COC("coc", "Deriv Stat Consciousness", "Level of awareness and alertness of the character."),
	UFO("ufo", "Deriv Stat Unconsciousness Fadeout Speed", "Speed at which unconsciousness effects diminish."),
	MUT("mut", "Deriv Stat Mute", "Status indicating whether the character is unable to speak."),
	PRB("prb", "Deriv Stat Perception Priority Boost", "Modifier that increases the priority of perception checks."),
	FPA("fpa", "Deriv Stat Food Poisoning Antidote", "Effectiveness of antidotes against food poisoning."),
	APA("apa", "Deriv Stat Alcohol Poisoning Antidote", "Effectiveness of antidotes against alcohol poisoning."),
	CAG("cag", "Deriv Stat Combat Aggression", "Determines how aggressively the character behaves during combat situations."),
	DEF("def", "Deriv Stat Defensiveness", "Measures the tendency of the character to prioritize defense in combat."),
	DRU("dru", "Deriv Stat Drunkenness", "Level of intoxication affecting character behavior and abilities."),
	POI("poi", "Deriv Stat Poisoning", "Degree to which the character is affected by poison."),
	POS("pos", "Deriv Stat Pocket Sight", "Ability to notice and detect pickpocketing or similar sneaky actions."),
	RAN("ran", "Deriv Stat Robbed Angriness", "Level of anger or aggression after being robbed."),
	IEX("iex", "Deriv Stat Item Expert", "Skill or knowledge level related to items, influencing their use or value."),
	HCM("hcm", "Deriv Stat Horse Courage Mod", "Modifier affecting a horse's bravery in dangerous or combat situations."),
	WAS("was", "Deriv Stat Ranged Weapon Aim Spread", "Spread or accuracy of ranged weapon aiming."),
	GRM("grm", "Deriv Stat Good Reputation Mod", "Modifier reflecting positive reputation impacts on the character."),
	BRM("brm", "Deriv Stat Bad Reputation Mod", "Modifier reflecting negative reputation impacts on the character."),
	DRT("drt", "Deriv Stat Dirtiness", "Degree of how dirty or unclean the character is, affecting perception and possibly interactions."),
	SML("sml", "Deriv Stat Smell", "Overall smell signature of the character, affecting stealth and detection."),
	SMI("smi", "Deriv Stat Smell Intensity", "Intensity or strength of the character's smell."),
	FRG("frg", "Deriv Stat Fragrance", "Pleasant scent level that might influence NPC reactions."),
	HKO("hko", "Deriv Stat Head Hit Knock Out Probability", "Chance of being knocked out when hit in the head."),
	ENC("enc", "Deriv Stat Encumbrance", "The load the character is carrying relative to their carrying capacity, affecting movement and stamina."),
	FDM("fdm", "Deriv Stat Fall Damage Multiplier", "Multiplier affecting the damage taken from falls."),
	SMA("sma", "Deriv Stat Sell Margin Adjust", "Adjustment to profit margins when selling items."),
	BMA("bma", "Deriv Stat Buy Margin Adjust", "Adjustment to cost margins when buying items."),
	HGS("hgs", "Deriv Stat Herb Gather Strength XP", "Experience gained from gathering herbs, influenced by this stat."),
	PDS("pds", "Deriv Stat Picklock Damage Speed", "Speed at which picklocks are damaged during lock picking attempts."),
	SHA("sha", "Deriv Stat Bow Self Harm Attack", "Chance or amount of self-inflicted damage when using a bow improperly."),
	PBM("pbm", "Deriv Stat Crafted Potions Buy Margin Adjust", "Adjustment to buying margins specifically for crafted potions."),
	RML("rml", "Deriv Stat Random Money Loot", "Amount or chance of random money found as loot."),
	HML("hml", "Deriv Stat Horse Throw Down Morale Limit", "Morale threshold that influences if a horse throws its rider."),
	BSO("bso", "Deriv Stat Basket Sufficiency Mod", "Modifier related to basket carrying capacity or stability."),
	BLD("bld", "Deriv Stat Bloodiness", "Level of blood or gore on the character, potentially affecting NPC reactions."),
	BBA("bba", "Deriv Stat Body Base Armor", "Base armor value provided by the character's body, excluding worn armor."),
	ARR("arr", "Deriv Stat Armor Rating", "Overall rating of the character's armor effectiveness."),
	JRM("jrm", "Deriv Stat Jail Recovery Speed Mod", "Modifier affecting the speed at which the character recovers from jail."),
	SUR("sur", "Deriv Stat Surrendering", "Indicates the tendency of the character to surrender in combat."),
	IMM("imm", "Deriv Stat Immortality", "Determines if the character is immune to damage or death."),
	APR("apr", "Deriv Stat Attack Protection", "Amount of protection the character has against attacks."),
	PPR("ppr", "Deriv Stat Pickpocket Protection", "Level of defense against pickpocketing attempts."),
	LTP("ltp", "Deriv Stat Loot Protection", "Protection level against theft or loss of loot."),
	UPR("upr", "Deriv Stat Unconsciousness Protection", "Resistance to becoming unconscious."),
	SKPR("skpr", "Deriv Stat Stealth Kill Protection", "Protection from stealth kill attempts."),
	KOPR("kopr", "Deriv Stat Knockout Protection", "Resistance to being knocked out."),
	CDS("cds", "Deriv Stat Cloth Dirtying Speed Km", "Speed at which clothing gets dirty during movement (per km)."),
	EDM("edm", "Deriv Stat Equipment Use Damage Multiplier", "Multiplier for damage taken by equipment during use."),
	PRC("prc", "Deriv Stat Picklock Return Chance", "Chance that a picklock returns after use."),
	CDW("cdw", "Deriv Stat Clinch Damage To Weapon", "Amount of damage to weapons during clinch fights."),
	EQW("eqw", "Deriv Stat Equipped Weight", "Total weight of currently equipped items."),
	PLA("pla", "Deriv Stat Plating Ratio", "Ratio of plated armor coverage."),
	WBC("wbc", "Deriv Stat Weapon Buff Charges", "Number of buff charges applied to weapons."),
	CBI("cbi", "Deriv Stat Charisma From Buffed Items", "Charisma bonus provided by buffed items."),
	NBI("nbi", "Deriv Stat Noise From Buffed Items", "Noise generated from buffed items affecting stealth."),
	ALC("alc", "Deriv Stat Alcoholism", "Level of alcoholism affecting the character."),
	MAP("map", "Deriv Stat Mean Attack Period", "Average time period between attacks."),
	ADM("adm", "Deriv Stat Alcohol Digest Mod", "Modifier for the rate of alcohol digestion."),
	ALM("alm", "Deriv Stat Alcohol Mood", "Mood influence caused by alcohol."),
	HOV("hov", "Deriv Stat Hangover", "Severity or duration of hangover effects."),
	BTW("btw", "Deriv Stat Boid Threat Weight", "Weight or influence of threats detected by AI boids."),
	OWL("owl", "Deriv Stat Owl", "Unknown or specific stat related to 'Owl' (context needed)."),
	RMS("rms", "Deriv Stat Real Move Speed Mod", "Modifier affecting the real movement speed of the character."),
	DEB("deb", "Deriv Stat Debauchery", "Represents the character's tendency towards debauchery or immoral behavior."),
	ACH("ach", "Deriv Stat Attack Charge", "Charge or buildup value before an attack."),
	PRS("prs", "Deriv Stat Persuade", "Effectiveness of the character's persuasion attempts."),
	IMP("imp", "Deriv Stat Impress", "Ability to impress or influence others."),
	DRD("drd", "Deriv Stat Dread", "Level of fear or intimidation the character projects or feels."),
	CRC("crc", "Deriv Stat Coerce", "Ability to coerce or force others to comply."),
	DMT("dmt", "Deriv Stat Dominate", "Level of dominance exerted by the character."),
	MGT("mgt", "Deriv Stat Might", "Measure of physical strength or power."),
	BAD("bad", "Deriv Stat Badassness", "Degree of toughness or intimidating presence."),
	NRV("nrv", "Deriv Stat Nervousness", "Level of nervousness or anxiety."),
	VAG("vag", "Deriv Stat Violence Angriness", "Aggression level related to violent anger."),
	MAG("mag", "Deriv Stat Material Angriness", "Angriness or frustration related to material issues."),
	AAG("aag", "Deriv Stat Average Angriness", "General average of anger levels."),
	RED("red", "Deriv Stat Random Event Difficulty", "Difficulty modifier for random events."),
	DRV("drv", "Deriv Stat Disabled Revive", "Indicates whether revival is disabled."),
	PMC("pmc", "Deriv Stat Permanent Corpse", "Indicates if a corpse remains permanently."),
	SDN("sdn", "Deriv Stat Service Denial", "Represents denial of services or interactions."),
	BRN("brn", "Deriv Stat Brand", "Represents a brand or mark on the character."),
	PLR("plr", "Deriv Stat Pillory", "Effect or status related to being in the pillory."),
	BEA("bea", "Deriv Stat Beating", "Represents damage or punishment from beating."),
	KKO("kko", "Deriv Stat Knock Out", "Chance or effect of knocking out an opponent."),
	SSE("sse", "Deriv Stat Stealth Kill Strength Effect", "Modifier for strength effects during stealth kills."),
	IES("ies", "Deriv Stat Injury Effects Suppress", "Reduces or suppresses injury effects on the character."),
	LRM("lrm", "Deriv Stat Lock picking Recognizable Mod", "Modifier for how recognizable lock picking attempts are."),
	PRM("prm", "Deriv Stat Pickpocketing Recognizable Mod", "Modifier for how recognizable pickpocketing attempts are."),
	UVH("uvh", "Deriv Stat Unaware Victim Hit Debuff", "Debuff applied when hitting an unaware victim."),
	UVA("uva", "Deriv Stat Unaware Victim Attack Bonus", "Bonus damage or effect when attacking an unaware victim."),
	CNP("cnp", "Deriv Stat Companion Nominal Price", "Base price value for a companion."),
	CBP("cbp", "Deriv Stat Companion Buying Price", "Price to buy a companion."),
	CSP("csp", "Deriv Stat Companion Selling Price", "Price gained from selling a companion."),
	SLP("slp", "Deriv Stat Companion Legalization Price", "Cost to legalize a companion."),
	CEP("cep", "Deriv Stat Companion Exchange Price", "Price related to companion exchanges."),
	ICP("icp", "Deriv Stat Is Companion Available To Purchase", "Boolean or flag indicating if companion is available for purchase."),
	CRP("crp", "Deriv Stat Craftsmanship Repair Price Mod", "Modifier reducing or increasing repair prices based on craftsmanship."),
	DFE("dfe", "Deriv Stat Dog Found Event Prob", "Probability modifier for dog found events."),
	CSC("csc", "Deriv Stat Combat Stamina Charged Regen", "Rate at which stamina regenerates when charged in combat."),
	HVP("hvp", "Deriv Stat Has Visible Perks UI", "Flag indicating whether perks UI is visible."),
	PQE("pqe", "Deriv Stat Pickpocketing Quick Escape", "Modifier for quick escape chance after pickpocketing."),
	SKS("sks", "Deriv Stat Shop Keeper Shadiness", "Modifier affecting shopkeepers' trust or honesty."),
	SST("sst", "Deriv Stat Stolen Item Selling Thievery XP", "XP gain modifier from selling stolen items related to thievery skill."),
	SSS("sss", "Deriv Stat Stolen Item Selling Stealth XP", "XP gain modifier from selling stolen items related to stealth skill."),
	XST("xst", "Deriv Stat Strength XP Gain Multiplier", "Multiplier for XP gain in strength skill."),
	XAG("xag", "Deriv Stat Agility XP Gain Multiplier", "Multiplier for XP gain in agility skill."),
	XVI("xvi", "Deriv Stat Vitality XP Gain Multiplier", "Multiplier for XP gain in vitality skill."),
	XSP("xsp", "Deriv Stat Speech XP Gain Multiplier", "Multiplier for XP gain in speech skill."),
	PXP("pxp", "Deriv Stat Prestige XP Gain Multiplier", "Multiplier for XP gain in prestige."),
	XSW("xsw", "Deriv Stat Weapon Sword XP Gain Multiplier", "Multiplier for XP gain in sword weapon skill."),
	XCR("xcr", "Deriv Stat Craftsmanship XP Gain Multiplier", "Multiplier for XP gain in craftsmanship skill."),
	XSU("xsu", "Deriv Stat Survival XP Gain Multiplier", "Multiplier for XP gain in survival skill."),
	XHW("xhw", "Deriv Stat Heavy Weapon XP Gain Multiplier", "Multiplier for XP gain in heavy weapons skill."),
	XMA("xma", "Deriv Stat Marksmanship XP Gain Multiplier", "Multiplier for XP gain in marksmanship skill."),
	XSC("xsc", "Deriv Stat Scholarship XP Gain Multiplier", "Multiplier for XP gain in scholarship skill."),
	SRR("srr", "Deriv Stat Stamina Hit Return Ratio", "Ratio affecting stamina returned upon hit."),
	BAP("bap", "Deriv Stat Black Arts Apprentice Potion Quality Bonus", "Bonus to potion quality for black arts apprentices."),
	ALP("alp", "Deriv Stat Alchemy Potion", "Effect or modifier related to alchemy potions."),
	ATD("atd", "Deriv Stat Able To Dodge", "Indicates ability to dodge attacks."),
	AMS("ams", "Deriv Stat Able To Master Strike", "Indicates ability to perform master strikes."),
	RCX("rcx", "Deriv Stat Repair Price To Crafting XP", "XP gain modifier from repair price."),
	LFB("lfb", "Deriv Stat Max Lock-picks From Blacksmithing", "Maximum lock-picks obtainable via blacksmithing."),
	TBA("tba", "Deriv Stat Thunderous Blast Active", "Indicates whether thunderous blast is active."),
	NRW("nrw", "Deriv Stat Perk No Rest For The Wicked Stamina Delta", "Stamina change for 'No Rest For The Wicked' perk."),
	FAC("fac", "Deriv Stat Frisk Avoid Chance", "Chance to avoid frisking."),
	AHE("ahe", "Deriv Stat Light Alcohol Healing Effect", "Healing effect from light alcohol."),
	APO("apo", "Deriv Stat Alcohol Positive Effects Offset", "Offset for positive alcohol effects."),
	ANO("ano", "Deriv Stat Alcohol Negative Effects Offset", "Offset for negative alcohol effects."),
	FPD("fpd", "Deriv Stat Forced Player Drunkenness", "Level of forced drunkenness on player."),
	EPH("eph", "Deriv Stat Every Potion Healing Effect", "Healing effect of every potion."),
	RPD("rpd", "Deriv Stat Reputation Propagation Distance Mod", "Modifier for how far reputation propagates."),
	RPR("rpr", "Deriv Stat Reputation Propagation Relation Mod", "Modifier for reputation propagation based on relation."),
	RPA("rpa", "Deriv Stat Reputation Propagation Ancestor Mod", "Modifier for reputation propagation through ancestors."),
	HLA("hla", "Deriv Stat Heavy Light Armor", "Modifier or value related to heavy/light armor."),
	RPP("rpp", "Deriv Stat Riposte Probability Penalty", "Penalty to riposte chance."),
	EFD("efd", "Deriv Stat Enable Fall Damage", "Flag or modifier to enable or disable fall damage."),
	AML("aml", "Deriv Stat Alcoholism Minimum Level", "Minimum alcoholism level required for effects."),
	BMR("bmr", "Deriv Stat Bushman RTPC", "RTPC related to bushman effect."),
	LGP("lgp", "Deriv Stat Last Gasp Protection", "Protection effect for last gasp."),
	BBN("bbn", "Deriv Stat Base Body Noise", "Base noise generated by the body."),
	SHD("shd", "Deriv Stat Shoe Health Decrease Multiplier", "Multiplier for shoe health degradation."),
	ATP("atp", "Deriv Stat Alco Teleport After Sleep Probability", "Probability to teleport after sleep under alcohol influence."),
	HLM("hlm", "Deriv Stat Hunter Loot Amount Mod", "Modifier for loot amount from hunting."),
	DIP("dip", "Deriv Stat Disabled Perfume", "Flag or modifier disabling perfume effects."),
	
	// Static Stats
	SHADINESS("shadiness", "Static Stat Shadiness", "Level of shadiness or suspiciousness of a character."),
	COMBAT_LEVEL("combatLevel", "Static Stat Combat Level", "Character's combat skill level."),
	INITIAL_DIRTINESS("initialDirtiness", "Static Stat Initial Dirtiness", "Starting level of dirtiness on character or item."),
	
	// Movement
	RUN("Run", "Run Speed", "Modifies the character's running speed. Positive values increase speed, negative values decrease it."),
	WALK("Walk", "Walk Speed", "Modifies the character's walking speed. Positive values increase speed, negative values decrease it."),
	LIMIT_SPRINT("LimitSprint", "Disable Sprinting", "Prevents the character from sprinting when present. This parameter works without a value—only its presence is required."),
	STAMINA_SPRINT("StaminaSprint", "Stamina Sprint Consumption", "Modifies the stamina consumption rate while sprinting. Higher values increase stamina usage, lower values reduce it."),
	HCD("hcd", "Hardcore Bad Back Flower Picking Chance", "Chance to trigger the Hardcore perk 'Bad Back' effect—Henry throws out his back—when picking flowers."),
	STAMINA_COOLDOWN_DEFAULT("StaminaCooldownDefault", "Default Stamina Cooldown", "Delay before stamina regeneration begins after general exertion."),
	STAMINA_COOLDOWN_ATTACK("StaminaCooldownAttack", "Stamina Cooldown After Attack", "Delay before stamina regeneration begins after performing an attack."),
	STAMINA_COOLDOWN_DODGE("StaminaCooldownDodge", "Stamina Cooldown After Dodge", "Delay before stamina regeneration begins after dodging."),
	STAMINA_COOLDOWN_HIT("StaminaCooldownHit", "Stamina Cooldown After Hit", "Delay before stamina regeneration begins after taking a hit."),
	STAMINA_COOLDOWN_BLOCK("StaminaCooldownBlock", "Stamina Cooldown After Block", "Delay before stamina regeneration begins after blocking an attack."),
	STAMINA_COOLDOWN_WEAPON_RAISED("StaminaCooldownWeaponRaised", "Stamina Cooldown with Weapon Raised", "Delay before stamina regeneration begins while holding a weapon in raised stance."),
	SPRINT("Sprint", "Sprint Speed Modifier", "Affects the character's sprinting speed."),
	SRC("src", "Combat Stamina Regen Reduction", "Reduces the default stamina regeneration rate during combat."),
	
	// Perks
	FBA("fba", "Seasoned Drinker Safety", "Ensures that when the character loses consciousness due to alcohol, they will always wake up in their own bedroom. This parameter is a boolean-style flag; a value of +1 enables the effect."),
	SKV("skv", "Dialogue Skill Check Modifier", "Scales the effectiveness of dialogue skill checks. The value represents a maximum multiplier (e.g., skv*1.16 = up to +16%). When used with AdjustableFadingWorldTimeTimed, the bonus scales dynamically—typically based on sleep duration—up to the defined maximum."),
	FVH("fvh", "Food Health Regeneration Bonus", "Increases health regeneration for a limited duration after consuming fruit or vegetables. The value defines the flat amount of additional health restored over the buff's lifetime (e.g., fvh+10 restores 10 extra health)."),
	LIP("lip", "Bone Fracture Prevention", "Prevents bone fractures by consuming charges of this buff. Each +1 negates one incoming fracture while the buff is active, though it is unclear whether multiple charges can stack to block multiple fractures."),
	SXM("sxm", "Trainer Experience Multiplier", "Multiplies experience gained from trainers. The value acts as a multiplier (e.g., sxm*1.2 grants +20% experience) and applies only to training-based skill progression during the buff's duration.");
	// fba - Seasoned Drinker - If you overdo it with alcohol and pass out, you will always wake up in the bed in your bedroom - fba+1 => skill activated
	// skv - Smooth Talker - For each hour of sleep in your bedroom (up to 8 hours), the difficulty of skill checks in dialogues is reduced by 2% for the next 24 hours - skv*1.16 => 16% maximum improvement. Hourly upgrade is presumably calculated in the background using Cpp:AdjustableFadingWorldTimeTimed
	// fvh - Carnival - Eating fruits and vegetables restores 10 more health over the next 24 hours => fvh+10
	// lip - Bone shield - Prevents the first bone fracture you would suffer in the next 24 hours => lip+1 (can multiple fractures be negated here?)
	// sxm - Apprentice - You receive a 20% experience bonus from trainers over the next 24 hours => sxm*1.2
	
	private final String key;
	private final String name;
	private final String description;
}